<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>AchievementLabs.SteamIdle</AssemblyName>
    <RootNamespace>AchievementLabs.SteamIdle</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile
      Include="..\..\third-party\steam-achievement-manager-7.0.41\SAM.API\**\*.cs"
      LinkBase="References\SAM.API"
      Exclude="..\..\third-party\steam-achievement-manager-7.0.41\SAM.API\GlobalSuppressions.cs;..\..\third-party\steam-achievement-manager-7.0.41\SAM.API\bin\**\*.cs;..\..\third-party\steam-achievement-manager-7.0.41\SAM.API\obj\**\*.cs" />
  </ItemGroup>

</Project>
