services:
  request-bot:
    build: .
    image: achievement-labs-request-bot:local
    container_name: achievement-labs-request-bot
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 9.9.9.9
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - ./.env:/app/.env:ro
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
